LANDABLE(g_landing_earth,	canLand,	s_notAllowedToLand)
LANDABLE(g_landing_isthur,	canLand,	s_notAllowedToLand)
LANDABLE(g_landing_gcs,		cannotLand,	s_shipUnidentified)
LANDABLE(g_landing_navier,	cannotLand,	s_planetQuarantined)
LANDABLE(g_landing_solomaw,	cannotLand,	s_notAllowedToLand)
